// KHDS7 Phase 1 Dashboard Data
// Auto-generated by dashboard_data_export.do
// Generated:  3 May 2026 23:31:21
window.KHDS7 = {

  // Section A: Interview Progress
  sectionA: {
    surveyDateFirst: "2026-02-05",
    surveyDateLast: "2026-03-01",
    hhInterviews: 454,
    totalG2: 941,
    deceased: 38,
    refused: 20,
    aliveNotRefused: 903,
    interviewed: 321,
    remaining: 562,
    totalPhase1: 2126,
    deceasedSource: "tracking",
    tiersInterviewed: [
      {name: "Baseline village", count: 205},
      {name: "Nearby village", count: 77},
      {name: "Elsewhere in Kagera", count: 39},
    ],
    tiersRemaining: [
      {name: "Baseline villages", count: 21},
      {name: "Kagera (other)", count: 139},
      {name: "Outside Kagera", count: 152},
      {name: "Not located", count: 250}
    ]
  },

  // Section B: G3 Progress
  sectionB: {
    g3OnRoster: 1042,
    g3CoResident: 1036,
    g3NonResRoster: 6,
    g3WithG2: 858,
    g3WithoutG2: 178,
    hhWithG3: 393,
    hhG3WithG2: 262,
    hhG3WithoutG2: 131,
    g3FatheredTotal: 475,
    g3FatheredAlive: 416,
    g2Asked: 310,
    locationG3: [
      {name: "Baseline village", count: 719},
      {name: "Nearby village", count: 220},
      {name: "Elsewhere in Kagera", count: 97}
    ],
    g3PerG2Roster: 3.23,
    g3PerG2Fathered: 1.30,
    g3PerG2Total: 4.52
  },

  // Section C: Interview Duration
  sectionC: {
    overall: {
      p25: 108.9,
      median: 138.8,
      p75: 182.7,
      mean: 151.7,
      n: 435
    }
  },

  // Section E: Not Located Reference
  sectionE: {
    location2010: [
      {label: "Baseline village", count: 53},
      {label: "Nearby village", count: 19},
      {label: "Elsewhere in Kagera", count: 46},
      {label: "Elsewhere in Tanzania", count: 38},
      {label: "Neighbouring country", count: 18},
      {label: "Not found in 2010", count: 76}
    ],
    lastSeen: [
      {label: "2010", value: 1, count: 174},
      {label: "2004", value: 2, count: 34},
      {label: "Wave 4", value: 3, count: 12},
      {label: "Wave 3", value: 4, count: 9},
      {label: "Wave 2", value: 5, count: 12},
      {label: "Wave 1", value: 6, count: 9}
    ],
    totalNotLocated: 250,
    totalNotLocatedAll: 285,
    notLocatedInterviewed: 35
  },

  // Metadata
  meta: {
    generated: " 3 May 2026 23:31:21",
    stataVersion: "19.5",
    phase1Villages: 17,
    totalVillages: 51
  }
};
